### PR TITLE
fix: avoids executing beforeEach and afterEach twice

### LINKED ISSUE #288: arquillian-junit5 runs @BeforeEach / @AfterEach code on client and server side in Container mode
##### Issue Overview

Converting tests to arquillian-junit5-container (version 1.7.0.Alpha5), I have the issue that the setup / teardown methods ( BeforeEach / AfterEach annotations) are executed twice when running tests in the container. 

One call is executed on the client, one call is executed on the server side. Tests with Junit 4 (arquillian-junit-container) ran these methods on the container side only. 

##### Expected Behaviour

BeforeEach / AfterEach are only executed once, and when the tests are run in container the execution must be on the server side. This was the behavior with Junit4, and for me the only useful way.  

##### Current Behaviour

The client side execution of these methods breaks the dependencies (because the code expects some runtime dependencies to be provided by the container). This causes exceptions which prevents the server side to be executed (which would be successful)

##### Steps To Reproduce
1. See attached project for example code

2. Define an In-Container Test with Junit 5 like below

3. if you run it, you will notice that the setup() is called on the client side and the server side. On the client side the injected @ArquillianResource is null, on the server side it is set. The JaxRS Client can not be instantiated on the client side without adding resteasy-client dependencies to the test, because the implementation is provided on the server side.

```
@ExtendWith(ArquillianExtension.class)
public class InContainerJunit5Test {
  private static final Logger LOG = LoggerFactory.getLogger(InContainerJunit5Test.class);
  
  @Deployment
  public static Archive<?> createTestArchive() {
    return ShrinkWrap.create(WebArchive.class, "arquillian-test.war").addPackages(true, "x1.wildfly.arquillian")
        .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml");
  }

  private String baseUrl;
  private Client client;
  private String expectedClientName;
  
  @ArquillianResource
  private URL url;
  
  @BeforeEach
  public void setup() {
    // this runs on client side now and on server side
    expectedClientName = System.getProperty("client.name", "Nobody");
    LOG.info("My name is '{}.'", expectedClientName);
    
    client = ClientBuilder.newClient();
  }
  
  @AfterEach
  public void teardown() {
    client.close();
  }
  
  @Test
  public void testResource() {
    ...
  }
```

##### Additional Information

Attached is a sample project containing a test with Junit4 and Junit5, which I deploy on Wildfly 21. If you have a running server instance, you can execute the tests with

```mvn -Pwildfly-managed -Djboss.home=/opt/wildfly-21.0.0.Final verify -Dclient.name=$USER```

Please excuse if this sample project is not completely self-contained, but I did not have much time yet. If you require it to reproduce the behavior, I will try to clean it up and upload it to github.

### PR DESCRIPTION
**Pull request by kifj**
#### Short description of what this resolves:

As raised in issue #288 the beforeEach and afterEach methods are executed twice if Arquillian tests are executed not "as client", but in a managed container. The first execution happens on the clients side and not in the deployment. This usually fails because injects and classes in the classpath are not available.

#### Changes proposed in this pull request:

- skip the execution if not in Arquillian 

Fixes #288 and may cause for #293, too.

### CODE REVIEW

**Comment by rimuln** [comment]
after looking in class. just question will not be same problem with beforeAll and afterAll?

**Comment by kifj** [comment]
> after looking in class. just question will not be same problem with beforeAll and afterAll?

Yes you're right. I've updated the PR.

**Comment by rimuln** [comment]
I have forked arquillian, and built locally with cherry pick your 2 commits and could confirm that helps for me too. Test on one class and test run fine. So vote to merge:) as it will fix #293 too. thx

**Comment by kifj** [comment]
Can I do something to proceed this PR? Do you need more information?

**Comment by lprimak** [comment]
Looks great

**Review by lprimak — APPROVED** [review]

**Comment by lprimak** [comment]
hey @bartoszmajsak Any chance to look at this and all the other PRs?
This one in particular is starging to hit really hard.
thank you!

**Comment by bartoszmajsak** [comment]
Sure, sorry for being away for a while. I'll work on them today.

**Review by bartoszmajsak — APPROVED** [review]
Thank you all involved for stepping in and reviewing this PR. And of course big thanks to @kifj for spending time fixing the problem!

**Pull request merged**
