### PR TITLE
feat(junit5): adds support for Suites

### PR DESCRIPTION
**Pull request by ingwarsw**
#### Short description of what this resolves:

This PR adds support for Suites in junit5 (in same way at it was working in junit4)
So it fixes Arquillian Suite Extension for junit5.

#### Changes proposed in this pull request:

Add suite finalizer based on auto closable objects on jupiter contexts.

Fixes https://github.com/ingwarsw/arquillian-suite-extension/issues/54

### CODE REVIEW

**Comment by lprimak** [comment]
@bartoszmajsak @Thihup Please merge this. It works perfectly and solves my issue!

**Comment by lprimak** [comment]
Spoke too soon :( TestContainer tests fail)

**Comment by ingwarsw** [comment]
@bartoszmajsak @Thihup Actually half of code in junit5 plugin can be removed (it was copy/pasted from junit4 and never used)..
I can try cleaning it in other PR..

**Comment by bartoszmajsak** [comment]
> @bartoszmajsak @Thihup Actually half of code in junit5 plugin can be removed (it was copy/pasted from junit4 and never used)..
> I can try cleaning it in other PR..

Awesome, many thanks. Also for all your great work over the years! (been using suite extension heavily in my previous projects).

**Review by bartoszmajsak — APPROVED** [review]

**Comment by bartoszmajsak** [comment]
@ingwarsw I've just released `1.7.0.Alpha6` with this patch. Waiting for more :)

**Comment by ingwarsw** [comment]
@bartoszmajsak Thanks..

I will probably find some spare time in next week.. that one is busy..

**Pull request merged**
