### PR TITLE
Arq 2034 new event

### PR DESCRIPTION
**Pull request by MatousJobanek**

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Pushed upstream

**Comment by Vampire** [comment]
Nice, can you say in which version this will be included?

**Comment by bartoszmajsak** [comment]
Next one which is just around the corner :) Working on the release now. Thanks for your help with testing it.

**Comment by Vampire** [comment]
Ah, nice, actually I didn't tested, but reported it, but I will probably test it when 1.1.12.Final is released. :-)

**Pull request closed without merging**
