### PR TITLE
Allow for setting the protocol in ServletProtocolConfiguration

### PR DESCRIPTION
**Pull request by hielkehoeve**
This pull request allows setting the protocol in ServletProtocolConfiguration. This way users can deploy using https and not have potentially sensitive data be send over http to the internet.

### CODE REVIEW

**Comment by aslakknutsen** [comment]
Yeah, interesting approach. Technically to fully support it I guess you would need configuration of keystores etc.

We've played with the idea of having a HTTPSConext in the ProtocolMetadata earlier and allow the containers to auto discover that info on deploy(). But that has always been discussed in the context of URL injection into the TestClass for client side tests, not for the in container test protocol.

How do you use this normally in your setup? You manually configure the Servlet protocol fully with schema/ip/port?  I'm guessing the auto discovered http port does not support https as well out of the box??

**Comment by hielkehoeve** [comment]
We have a setup where we can run on a localhost wildfly and on a remote wildfly without changing a line of code (i guess everyone would want this). By defining a default container 'wildfly' for localhost and a container 'wildfly-remote' for remote and using the magical property 'containerNameMap' we can switch between the 2 'endpoints'. 

Our pom has 2 profiles which provide the 'wildfly-arquillian-container-managed' or 'wildfly-arquillian-container-domain-remote' respectively.

Both profiles work perfectly except for when i want to use https to run the tests.

On the command line we use these properties:
```
-Dwildfly.mgnt.user=deploy -Dwildfly.mgnt.password=deploy -Dwildfly.mgnt.host=x.x.x.x -Drest.host=myrestfullhostname.nl -Darquillian.scheme=https -Darquillian.port=443 -Darquillian.launch=wildfly-remote
```

our arquillian.xml contains:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<arquillian xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://jboss.org/schema/arquillian"
	xsi:schemaLocation="http://jboss.org/schema/arquillian
       http://jboss.org/schema/arquillian/arquillian_1_0.xsd">
	<container qualifier="wildfly" default="true">
		<configuration>
			<property name="allowConnectingToRunningServer">true</property>
			<property name="javaVmArguments">-Xms1g -Xmx4g</property>
		</configuration>
	</container>

	<container qualifier="wildfly-remote">
		<configuration>
			<property name="username">${wildfly.mgnt.user:}</property>
			<property name="password">${wildfly.mgnt.password:}</property>
			<property name="managementAddress">${wildfly.mgnt.host:localhost}</property>
			<property name="containerNameMap">arquillian=wildfly</property>
		</configuration>
	</container>

	<defaultProtocol type="Servlet 3.0">
		<property name="scheme">${arquillian.scheme:http}</property>
		<property name="host">${rest.host:myrestfullhostname.localhost.nl}</property>
		<property name="port">${arquillian.port:8080}</property>
	</defaultProtocol>
</arquillian>
```

our deployment is created using the following annotations:
```
@Deployment
@TargetsContainer("wildfly")
public static EnterpriseArchive createDeployment()
{
    ...
}
```

**Comment by hielkehoeve** [comment]
```
Yeah, interesting approach. Technically to fully support it I guess you would need configuration of keystores etc.
```

It's only necessary if you use self-signed certificates, which doesn't seem a decent approach to me. The changes of this pull request will allow communication using proper ssl certificates. No additional configuration, other than the scheme, was required.

**Comment by hielkehoeve** [comment]
Created my own version of arquillian-core for the time being. I'll receive a notification if you decide to merge/delete this pull request.

**Comment by aslakknutsen** [comment]
Thank you! Pushed upstream; https://github.com/arquillian/arquillian-core/commit/60932e7824e990f6c11ef143a97a20c3faa912fe 

See https://issues.jboss.org/browse/ARQ-1978 for related feature request. :)

**Pull request closed without merging**
