### PR TITLE
ARQ-1976 All ResourceProvider#canProvide implementations could try to inject subtypes

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/ARQ-1976

@aslakknutsen this would really need your eyes, this might be problematic.

### CODE REVIEW

**Comment by aslakknutsen** [comment]
hmm, nicely spotted.. Agree, this looks wrong. Probably an attempt to be open for extension, but.. the context lookup is 'ContainerController' and the WildFlyContainerController is registered under it's own type if I remember correctly, instead of attempting to overwrite the 'core' ContainerController.

**Comment by rhusar** [comment]
Yes, the are separate. However, WildFlyContainerController interface extends ContainerController interface, and thus, on an arbitrary order of how the ResourceProviders are registered, the ContainerControllerProvider's canProvide implementation will try to provide ContainerController for desired type WildFlyContainerController - which has to fail.

**Comment by aslakknutsen** [comment]
correct. :)

**Comment by aslakknutsen** [comment]
Thank you, pushed upstream https://github.com/arquillian/arquillian-core/commit/d956e16b9c1e6ef84b12dbf9a9940bc8f9b9deac

**Pull request closed without merging**
