### PR TITLE
ARQ-2231 The JUnit 5 container does not work with manual mode tests

### PR DESCRIPTION
**Pull request by rhusar**
https://issues.redhat.com/browse/ARQ-2231

### CODE REVIEW

**Review by jamezp — APPROVED** [review]

**Review by petrberan — CHANGES_REQUESTED** [review]
Just putting it here, but this fails main branch build of https://github.com/jbossws/jbossws-cxf

**Comment by rhusar** [comment]
Thanks @petrberan for pointing this out - given that the cxf testsuite is doing pretty convoluted code paths, until we figure our where the problem is, converting to draft. Perhaps the double events are now defacto the norm.

**Comment by jamezp** [comment]
I  don't know how we can stop these things from happening twice, but if I use this PR and add an empty `@BeoreEach` method the test will pass. So maybe we do need it executed twice, though it does feel like it should be done twice.

**Comment by rhusar** [comment]
Thanks @jamezp 

Rebased only now to remove the merge commits/pull in latest changes and run CI, no changes.

**Review by jamezp — APPROVED** [review]

**Pull request merged**
