### PR TITLE
Introduce new protocol/servlet module for Jakarta

### LINKED ISSUE #248: Arq. servlet protocol and Jakarta EE 9
I recently started trying out Weld servlet with Jakarta EE 9 since there is now a Tomcat version for it.
See [this related JIRA](https://issues.redhat.com/browse/WELD-2630) issue.

In that I figured that we are still using some Arq. to perform the testing, namely Arq. servlet protocol.
[These bits](https://github.com/arquillian/arquillian-core/blob/master/protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/runner/ServletTestRunner.java#L27-L29) are still outdated and use `javax` namespace which then causes failures (CNFE) during bootstrap.

Quick-scanning the code, I think we just need to swap [this](https://github.com/arquillian/arquillian-core/blob/master/protocols/servlet/pom.xml#L60-L66) dependency and then change the namespaces accordingly within any related classes. But I have yet to try that (on it now).

However, I am not quite sure how we want to approach this with Arq. - whether we just update the core, or whether you want a separate EE 9 module for this. WDYT @bartoszmajsak?

FYI @starksm64

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #248 

Adds new module that copies over things from `protocols/servlet` and uses `jakarta` dependency instead of `javax`. Also updates Jetty test dep to 11 which runs on EE 9. However, this changes makes it so that I can only run it with JDK 11 so we will need to change the CI execution (which I can add to this PR if we agree on that).

Second commit prunes the new module and removes the notion of version 2.5 and 3 support because (unless I am mistaken) EE 9 means servlet v4 and you cannot really run anything older due to the namespace change.

### CODE REVIEW

**Comment by manovotn** [comment]
Actually, added a commit to bump Travis to use JDK 11, let's see what that happens.

Meanwhile, I will use this PR as basis for https://github.com/arquillian/arquillian-container-tomcat/issues/86 and report back once I have a working setup.

Any comments here are welcome of course. I admit I am not familiar with how Arq. does servlet protocol so I kind of did a semi-blind copy-paste and hoped for the best :-D

**Comment by bartoszmajsak** [comment]
Humm did we both miss #246?

**Comment by manovotn** [comment]
Uff, looks like we did. I mean, no surprise, it doesn't have an issue an not even a mention of either of us :-/

**Comment by manovotn** [comment]
Let's go with Scott's version, they are pretty similar but his is more polished already. I've just rebased my Tomcat adapter work on that, it was a rather easy change. So closing this one.

**Pull request closed without merging**
