### PR TITLE
fix(release): changes javadoc settings for JDK 11+

### LINKED ISSUE #414: Unable to build with -Prelease due to javadoc error
##### Issue Overview

The current release build is failing if the release profile is enabled due to a javadoc error.

##### Expected Behaviour
The release builds

##### Current Behaviour
The build fails when generating the javadoc for the arquillian-core-api module:

```
1 error
[INFO] FAILURE build of project org.jboss.arquillian.core:arquillian-core-api
[INFO] Builder state: blocked=0 finished=1 ready-or-running=0 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.942 s (Wall Clock)
[INFO] Finished at: 2022-07-27T21:53:08-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:javadoc (default-cli) on project arquillian-core-api: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - javadoc: warning - The old Doclet and Taglet APIs in the packages
[ERROR] com.sun.javadoc, com.sun.tools.doclets and their implementations
[ERROR] are planned to be removed in a future JDK release. These
[ERROR] components have been superseded by the new APIs in jdk.javadoc.doclet.
[ERROR] Users are strongly recommended to migrate to the new APIs.
[ERROR] javadoc: error - invalid flag: -Xdoclint:none
[ERROR] 
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/starksm/Dev/JBoss/Weld/arquillian-core/core/api/target/site/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

##### Steps To Reproduce
1. cd arquillian-core/core/api
2. mvn -Prelease compile javadoc:javadoc

##### Additional Information

```
<details>
 <summary>$mvn --version</summary>
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /usr/local/Cellar/maven/3.8.4/libexec
Java version: 11.0.16, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.5", arch: "x86_64", family: "mac"
</details>
```
I am seeing the same problem on another linux build system as well. The full output of the mvn -X command and options file passed to the javadoc command is attached in the build.log file.

[build.log](https://github.com/arquillian/arquillian-core/files/9205137/build.log)

### PR DESCRIPTION
**Pull request by bartoszmajsak**
* updates maven-javadoc-plugin to latest 3.4.0
  * swaps UML doclet to alternative working with latest JDKs
  * removes jboss-compiler overwrite as it's been fixed

Fixes #414

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
I spent some time looking at the problem and it's opening a can of worms :) Here are the issues I've encountered

### APIViz doclet compatibility

This doclet implementation is from pre JDK8 times. There's [updated fork](https://github.com/grahamedgecombe/apiviz/), but even with this one does not work for JDK 11

The alternative we can use is:

```
<doclet>nl.talsmasoftware.umldoclet.UMLDoclet</doclet>
<docletArtifact>
	<groupId>nl.talsmasoftware</groupId>
    <artifactId>umldoclet</artifactId>
    <version>2.x</version>
</docletArtifact>
```

If we want to keep UML diagrams as part of our javadoc. It seems to work fine.

#### Changes in javadoc

After disabling the doclet I started seeing more errors

```
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (attach-javadocs) on project arquillian-container-te
st-api: MavenReportException: Error while generating Javadoc:                                                                                     
[INFO] [ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8
/docs/api/ are in the unnamed module.                                                                                                             
[INFO] [ERROR] /home/bartek/code/redhat/arquillian/arquillian-core/container/test-api/src/main/java/org/jboss/arquillian/container/test/api/Deploy
ment.java:29: warning - Tag @link: reference not found: Archive                                                                                   
[INFO] [ERROR] /home/bartek/code/redhat/arquillian/arquillian-core/container/test-api/src/main/java/org/jboss/arquillian/container/test/api/Deploy
ment.java:29: warning - Tag @link: reference not found: Descriptor
```

Luckily bumping it to the latest version seems to solve the problem. 

But this raises a question - who is maintaining [https://github.com/jboss/jboss-parent-pom/](https://github.com/jboss/jboss-parent-pom/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)? It has updates to plugins we rely on (such as javadoc plugin) instead of overwriting it here.

**Comment by chengfang** [comment]
@bartoszmajsak,  @dmlloyd maintain jboss-parent. You may want to raise an issue and PR there.

**Comment by bartoszmajsak** [comment]
@chengfang PRs are raised by dependabot so it's a matter of merging them and cutting the release. I'll ping David, thanks.

**Review by chengfang — APPROVED** [review]

**Comment by chengfang** [comment]
BTW, I also use apiviz in other project (https://github.com/jberet/jsr352/blob/master/pom.xml#L178), which releases regularly with JDK 8 and 11, but haven't seen this error. Not sure what differs. I'll keep a note to double check in the other project.

**Review by starksm64 — APPROVED** [review]

**Comment by bartoszmajsak** [comment]
@chengfang Maybe it all boils down to 

https://github.com/jberet/jsr352/blob/36a172aa7db0ea25e53a3122077801f02408014b/pom.xml#L185-L187

which I missed.

**Pull request merged**
