### PR TITLE
Fixes false positive for in container tests

### PR DESCRIPTION
**Pull request by dipak-pawar**
#### Short description of what this resolves:
This fixes false positive for in container tests

#### Changes proposed in this pull request:

- Throwing exception to get in back on client side in case of failure

**Fixes**: #149

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Thanks @dipak-pawar. Just wondering - do we have a test revealing this bug somewhere?

**Comment by dipak-pawar** [comment]
@bartoszmajsak nopes. But I am not sure How can we write unit tests for in-container deployment?

**Comment by bartoszmajsak** [comment]
I didn't mean unit test :)

**Comment by dipak-pawar** [comment]
I will try to write it today.

**Pull request merged**
