### PR TITLE
chore: enable Dependabot v2

### PR DESCRIPTION
**Pull request by sullis**
#### Short description of what this resolves:

This PR enables Dependabot v2

https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

#### Changes proposed in this pull request:

add dependabot.yml

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Hi, thanks for your contribution. I'm just wondering - since we are using dependabot without explicit config file doesn't it mean we are already on v2?

**Comment by manovotn** [comment]
Just accidentally stumbled across this issue while googling pretty much the same thing.
Apparently using dependabot the way you do here is a "non-native" approach and you can now do a native one via project's `Insights` -> `Dependency Graph` -> `Dependabot`. This then leads to creation of the aforementioned config file.

Though I am not sure what are the perks of this versus having it without config file. I'd say for now you can happily keep using the current one...

**Comment by starksm64** [comment]
Following up on @manovotn comment, the current use of the Dependabot Preview will be shut down on August 3rd, 2021:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/upgrading-from-dependabotcom-to-github-native-dependabot

To keep Dependabot updated we need to merge the #333 PR that dependabot-preview created, and also has the warning about the preview version being shutdown.

It looks like the only feature in the preview that we use that is not currently in the native version is live updates.

**Comment by starksm64** [comment]
So in other words, this PR is obsoleted by #333

**Comment by bartoszmajsak** [comment]
Then I guess we can close this one in favor of #333.

**Pull request closed without merging**
