### PR TITLE
fix: typo in the servlet 5.0 protocol for jetty

### PR DESCRIPTION
**Pull request by olamy**
- fix typo and add simple github actions to check the build of PRs
- no need of multiple jdks
- add dependabot as well

#### Changes proposed in this pull request:

-
-
-

Fixes #

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Thanks for these improvements @olamy. I just wonder why do we need `.github/workflows/maven.yml` since we have CircleCI jobs?

**Comment by olamy** [comment]
ah yup. I just find gh actions more and integrated with github source code.
but yeah if it bother you I can remove it.

**Comment by olamy** [comment]
@bartoszmajsak  removed

**Review by bartoszmajsak — APPROVED** [review]
Thank you!

**Pull request merged**
