### PR TITLE
ARQ-2034 Added JUnitRemoteExtension containing RulesEnricher into the deployment archive and registered

### PR DESCRIPTION
**Pull request by MatousJobanek**
Now, the injection into the `@Rule` should work also on the container side

---

This change is [Reviewable](https://reviewable.io/reviews/arquillian/arquillian-core/110)

### CODE REVIEW

**Comment by MatousJobanek** [comment]
Realized that this is not the best solution - the "delegated enrichers" are now called twice - in BeforeRules phase and in Before phase as a part of the standard enrichment process. This causes that instances of injected (cdi or ejb) beans differ in BeforeRules from the ones that are injected in Before.

**Comment by bartoszmajsak** [comment]
Shall we close this PR and you send a new when you find the proper solution? Or maybe you need some help here?

**Comment by MatousJobanek** [comment]
Keep it open for a while - I'll sent here additional commits, so we can discuss them...

**Comment by Vampire** [comment]
@MatousJobanek is this only bad in specific situations or generally? Because I implemented this fix as workaround in our codebase, yet we do not do much Arquillian tests yet, so we might not have hit the problem yet.

**Comment by MatousJobanek** [comment]
I found out that it is not a big deal - it should be quite easily solved by appropriate scope.

**Comment by Vampire** [comment]
I'm sorry, but I didn't understand your answer. Does that mean it is no problem as I have it in our code, or that I have to do something to make it work correctly. Who would have to scope what where?

**Comment by MatousJobanek** [comment]
I meant that it's not a big problem that the enrichers are called twice - in BeforeRules phase and in Before phase. The thing, that instances of injected beans differ in BeforeRules from the ones that are injected in Before phase are quite expected behaviour - for a request-scoped beans, so by changing the scope of the bean can be easily solved this "impact".

**Comment by MatousJobanek** [comment]
So yeah, it's not a problem that you have it in your code, unless you write your own enricher with unexpected behaviour that wouldn't be compatible with this "event-flow".

**Comment by bartoszmajsak** [comment]
@MatousJobanek can we aim to release this feature as part of next release? Just bundling some stuff together and I'm wondering how far we are with this functionality to be considered done?

**Comment by MatousJobanek** [comment]
Yes, but we should also consider this solution [1] containing one additional commit [2] that solves the second point of this issue: https://issues.jboss.org/browse/ARQ-2034

[1] https://github.com/MatousJobanek/arquillian-core/tree/ARQ-2034_new_event
[2] https://github.com/MatousJobanek/arquillian-core/commit/f3fe5a5658fce7692e901e1d463a35e75c8617d3

**Comment by bartoszmajsak** [comment]
Closing in favor of #121

**Pull request closed without merging**
