### PR TITLE
[Feat] Add arquillian scheduling

### PR DESCRIPTION
**Pull request by dimchoSCR**
This change is [Reviewable](https://reviewable.io/reviews/arquillian/arquillian-core/112)

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Hi Dimcho,

many thanks for all your great work during Google Summer of Code. I think this piece of functionality deserves its own extension so that we can continue moving it forward independently from the Core. I will take care of moving this changeset to its new repository this week.

WDYT @aslakknutsen?

**Comment by aslakknutsen** [comment]
Good work!

Yeah, probably should be it's own extension.

**Comment by dimchoSCR** [comment]
Hi Bartosz, Aslak, 

thank you both for your help this summer! It'll be great to see the project evolve and grow over time in its own repository. I'll continue working on it and fix any potential problems as well. I had an awesome time this Google Summer of Code!

**Comment by lordofthejars** [comment]
@bartoszmajsak have you started the movement to its own extension or you  want I take care of it?

**Comment by bartoszmajsak** [comment]
I will.

**Comment by bartoszmajsak** [comment]
Closing as the whole concept evolved to https://github.com/arquillian/smart-testing/

Thanks @dimchoSCR for your great work which was the foundation for new tool! I hope to see you involved in there!

**Pull request closed without merging**
