### PR TITLE
[576] Add back the afterAll and beforeEach callbacks. The TestRu…

### LINKED ISSUE #576: wildfly-arquillian build against arquillian-core 1.8.1.Final fails junit test
##### Issue Overview
Update the 
##### Expected Behaviour
all tests should pass

##### Current Behaviour
wildfly-arquillian-junit-api fails with
```
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.899 s <<< FAILURE! -- in org.wildfly.arquillian.junit.integration.InContainerRequireModuleIT
[ERROR] org.wildfly.arquillian.junit.integration.InContainerRequireModuleIT.pass -- Time elapsed: 0.113 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: not <null>
        at deployment.4890d11c-8b48-4663-8d76-1572d0bcc037.war//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
        at deployment.4890d11c-8b48-4663-8d76-1572d0bcc037.war//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at deployment.4890d11c-8b48-4663-8d76-1572d0bcc037.war//org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:49)
        at deployment.4890d11c-8b48-4663-8d76-1572d0bcc037.war//org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:35)
        at deployment.4890d11c-8b48-4663-8d76-1572d0bcc037.war//org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:30)
        at deployment.4890d11c-8b48-4663-8d76-1572d0bcc037.war//org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:304)
        at deployment.4890d11c-8b48-4663-8d76-1572d0bcc037.war//org.wildfly.arquillian.junit.integration.InContainerRequireModuleIT.pass(InContainerRequireModuleIT.java:46)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at deployment.4890d11c-8b48-4663-8d76-1572d0bcc037.war//org.jboss.arquillian.junit5.ArquillianExtension.interceptTestMethod(ArquillianExtension.java:69)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

```
##### Steps To Reproduce
1. clone https://github.com/wildfly/wildfly-arquillian.git
2. update version.org.jboss.arquillian.core to 1.8.1.Final in root pom.xml
3. cd wildfly-arquillian
4. mvn install

##### Additional Information

Anything relevant to help us resolving the problem. For example if you are using `mvn` you can share output for `mvn --version` as well as dependencies in use `mvn dependency:tree`. OS as well as JDK version would be helpful too.

For long outputs such as stacktraces please use HTML5 `<details>`

```
starksm@Scotts-Mac-Studio wildfly-arquillian % mvn --version
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /Users/starksm/bin/apache-maven-3.9.6
Java version: 21.0.1, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.7.5", arch: "aarch64", family: "mac"
```

### PR DESCRIPTION
**Pull request by jamezp**
…nnerAdaptor.before() and TestRunnerAdaptor.after() need to happen in the beforeEach and afterEach listeners.

#### Short description of what this resolves:

The `BeforeEachCallback` and `AfterEachCallback` callbacks need to be added back for JUnit 5. It looks like the resource injection needs to happen in this context to work.

resolves #576

### CODE REVIEW

**Comment by lprimak** [comment]
Any chance you can test / merge https://github.com/arquillian/arquillian-core/pull/314 ?
JUnit 5 lifecycle tests

**Comment by lprimak** [comment]
Also why is TestNG container failing?

**Comment by jamezp** [comment]
> Any chance you can test / merge #314 ? JUnit 5 lifecycle tests

I think we need to decide whether we should be running tests requiring implementations here, or if the implementations should be testing with CI and SNAPSHOT builds.

For https://github.com/wildfly/wildfly-arquillian I was planning on adding SNAPSHOT testing there for each push and a nightly job.

**Comment by jamezp** [comment]
> Also why is TestNG container failing?

I'm not sure I follow, what do you mean by TestNG failing?

**Comment by lprimak** [comment]
Testing https://github.com/flowlogix/test-arq-suite/tree/TestNG with Arquillian 1.8.1.Final fails.
1.8.0.Final succeeds. This fix only touches JUnit5 yet there is still something wrong with TestNG container

**Comment by jamezp** [comment]
> Testing https://github.com/flowlogix/test-arq-suite/tree/TestNG with Arquillian 1.8.1.Final fails. 1.8.0.Final succeeds. This fix only touches JUnit5 yet there is still something wrong with TestNG container

This fix is only for JUnit 5. I'm not sure what would fail with TestNG. I don't really see anything obvious, but you could file a new issue. The error seems to be something like:
```
Caused by: java.lang.reflect.MalformedParameterizedTypeException: Mismatch of count of formal and actual type arguments in constructor of org.jboss.arquillian.container.spi.Container: 0 formal argument(s) 1 actual argument(s)
	at java.base/sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:59)
	at java.base/sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:52)
	at java.base/sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:100)
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.repository.FieldRepository.computeGenericType(FieldRepository.java:90)
	at java.base/sun.reflect.generics.repository.FieldRepository.getGenericType(FieldRepository.java:82)
	at java.base/java.lang.reflect.Field.getGenericType(Field.java:276)
	at org.jboss.arquillian.core.impl.InjectionPointImpl.getType(InjectionPointImpl.java:61)
	at org.jboss.arquillian.core.impl.ManagerImpl.injectInstances(ManagerImpl.java:492)
	at org.jboss.arquillian.core.impl.ManagerImpl.inject(ManagerImpl.java:483)
	at org.jboss.arquillian.core.impl.ManagerImpl.inject(ManagerImpl.java:184)
	at org.jboss.arquillian.core.impl.InjectorImpl.inject(InjectorImpl.java:54)
	at org.jboss.arquillian.container.impl.LocalContainerRegistry.create(LocalContainerRegistry.java:73)
	... 69 more
```

Anyway, that's definitely a different issue.

**Comment by lprimak** [comment]
Unfortunately I can't do a "real" test yet b/c Jakarta 1.8.1 isn't synced to maven central yet...

**Comment by starksm64** [comment]
It is synched now:
https://repo.maven.apache.org/maven2/org/jboss/arquillian/protocol/arquillian-protocol-servlet-jakarta/1.8.1.Final/
[arquillian-protocol-servlet-jakarta-1.8.1.Fin...](https://repo.maven.apache.org/maven2/org/jboss/arquillian/protocol/arquillian-protocol-servlet-jakarta/1.8.1.Final/arquillian-protocol-servlet-jakarta-1.8.1.Final-javadoc.jar)  2024-07-01 23:07    293766      
[arquillian-protocol-servlet-jakarta-1.8.1.Fin...](https://repo.maven.apache.org/maven2/org/jboss/arquillian/protocol/arquillian-protocol-servlet-jakarta/1.8.1.Final/arquillian-protocol-servlet-jakarta-1.8.1.Final-javadoc.jar.md5)  2024-07-01 23:07        32      
[arquillian-protocol-servlet-jakarta-1.8.1.Fin...](https://repo.maven.apache.org/maven2/org/jboss/arquillian/protocol/arquillian-protocol-servlet-jakarta/1.8.1.Final/arquillian-protocol-servlet-jakarta-1.8.1.Final-javadoc.jar.sha1)  2024-07-01 23:07        40      
[arquillian-protocol-servlet-jakarta-1.8.1.Fin...](https://repo.maven.apache.org/maven2/org/jboss/arquillian/protocol/arquillian-protocol-servlet-jakarta/1.8.1.Final/arquillian-protocol-servlet-jakarta-1.8.1.Final-sources.jar)  2024-07-01 23:07     48747      
[arquillian-protocol-servlet-jakarta-1.8.1.Fin...](https://repo.maven.apache.org/maven2/org/jboss/arquillian/protocol/arquillian-protocol-servlet-jakarta/1.8.1.Final/arquillian-protocol-servlet-jakarta-1.8.1.Final-sources.jar.md5)  2024-07-01 23:07        32      
[arquillian-protocol-servlet-jakarta-1.8.1.Fin...](https://repo.maven.apache.org/maven2/org/jboss/arquillian/protocol/arquillian-protocol-servlet-jakarta/1.8.1.Final/arquillian-protocol-servlet-jakarta-1.8.1.Final-sources.jar.sha1)  2024-07-01 23:07        40      
[arquillian-protocol-servlet-jakarta-1.8.1.Fin...](https://repo.maven.apache.org/maven2/org/jboss/arquillian/protocol/arquillian-protocol-servlet-jakarta/1.8.1.Final/arquillian-protocol-servlet-jakarta-1.8.1.Final.jar)  2024-07-01 23:07     58927      
[arquillian-protocol-servlet-jakarta-1.8.1.Fin...](https://repo.maven.apache.org/maven2/org/jboss/arquillian/protocol/arquillian-protocol-servlet-jakarta/1.8.1.Final/arquillian-protocol-servlet-jakarta-1.8.1.Final.jar.md5)  2024-07-01 23:07        32      
[arquillian-protocol-servlet-jakarta-1.8.1.Fin...](https://repo.maven.apache.org/maven2/org/jboss/arquillian/protocol/arquillian-protocol-servlet-jakarta/1.8.1.Final/arquillian-protocol-servlet-jakarta-1.8.1.Final.jar.sha1)  2024-07-01 23:07        40      
[arquillian-protocol-servlet-jakarta-1.8.1.Fin...](https://repo.maven.apache.org/maven2/org/jboss/arquillian/protocol/arquillian-protocol-servlet-jakarta/1.8.1.Final/arquillian-protocol-servlet-jakarta-1.8.1.Final.pom)  2024-07-01 23:07      2875      
[arquillian-protocol-servlet-jakarta-1.8.1.Fin...](https://repo.maven.apache.org/maven2/org/jboss/arquillian/protocol/arquillian-protocol-servlet-jakarta/1.8.1.Final/arquillian-protocol-servlet-jakarta-1.8.1.Final.pom.md5)  2024-07-01 23:07        32      
[arquillian-protocol-servlet-jakarta-1.8.1.Fin...](https://repo.maven.apache.org/maven2/org/jboss/arquillian/protocol/arquillian-protocol-servlet-jakarta/1.8.1.Final/arquillian-protocol-servlet-jakarta-1.8.1.Final.pom.sha1)  2024-07-01 23:07        40

**Review by starksm64 — APPROVED** [review]

**Comment by lprimak** [comment]
Confirmed. Both TestNG and JUnit 5 work with the latest SNAPSHOT.

**Pull request merged**
