### PR TITLE
[ARQ-2107][ARQ-2109] improve @EJB and @Resource enrichers

### PR DESCRIPTION
**Pull request by Ladicek**
**Fixes**: https://issues.jboss.org/browse/ARQ-2107 https://issues.jboss.org/browse/ARQ-2109

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Thanks for these fixes @Ladicek. Can you also check if it would make sense to cover them in the tests we have for both modules?

**Comment by Ladicek** [comment]
@bartoszmajsak thanks for looking into this. I've briefly considered adding tests and concluded I don't know how I woud do that. Specifically:

- For `@Resource`, if I were to add a class with `@Resource(lookup=...)`, I'd either have to rely on Java 7 (and Arquillian seems to be on Java 5 or 6) or I'd have to bring in a Java EE 6 API dependency and somehow make sure that it will take precedence (which looks brittle, see http://stackoverflow.com/questions/32991207/maven-build-uses-jdk-home-src-zip-javax-annotation-resource-java-not-dependency or http://www.mastertheboss.com/jboss-frameworks/maven-tutorials/jboss-maven/solving-the-resource-lookup-compilation-issue).
- For `@EJB`, I'm just expanding the set of heuristics for one more option. I can only think of testing that the set of heuristics actually used contains some well-known patterns, but I don't think it would add much.

WDYT?

**Comment by bartoszmajsak** [comment]
> For @Resource, if I were to add a class with @Resource(lookup=...), I'd either have to rely on Java 7 (and Arquillian seems to be on Java 5 or 6) or I'd have to bring in a Java EE 6 API dependency and somehow make sure that it will take precedence (which looks brittle, see http://stackoverflow.com/questions/32991207/maven-build-uses-jdk-home-src-zip-javax-annotation-resource-java-not-dependency or http://www.mastertheboss.com/jboss-frameworks/maven-tutorials/jboss-maven/solving-the-resource-lookup-compilation-issue).

Totally agree - that was my thought as well.

> For @EJB, I'm just expanding the set of heuristics for one more option. I can only think of testing that the set of heuristics actually used contains some well-known patterns, but I don't think it would add much.

Yeah from the unit testing perspective that won't add much.

Are you testing it somewhere though? e.g. WF Swarm?

**Comment by Ladicek** [comment]
I do have tests for Swarm that I want to submit that excersise these changes. Here's a WIP branch: https://github.com/Ladicek/wildfly-swarm/commits/test-arquillian-enrichers However, I can't submit those tests just yet because there's no Arquillian release that contains them :-) And when trying to run the test locally with a SNAPSHOT build, I found a Swarm issue as well (https://issues.jboss.org/browse/SWARM-1326).

**Comment by bartoszmajsak** [comment]
Thanks for your contributiokn

**Pull request merged**
