### PR TITLE
#125: Consolidate Arquillian Documentation to GitHub Repo

### PR DESCRIPTION
**Pull request by hemanik**
#### Short description of what this resolves:
Consolidates Arquillian documentation from Confluence to GitHub Repo.

#### Changes proposed in this pull request:

- Adds documentation section to the repo holding all the documentation for the project.

**Fixes**: #125

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Running `asciidoctor README.adoc -a asciidoctor-source=./docs -o index.html` does not render the whole documentation. Just what's in the README

**Comment by hemanik** [comment]
`asciidoctor README.adoc -a asciidoctor-source=./docs -o index.html` would render just the README since you specify only that and also just a single output file `index.html`.

For the whole documentation, I tried giving multiple files as `asciidoctor example1.adoc example2.adoc` and it works. 

Probably not a good way, but I couldn't find any better way.

**Comment by bartoszmajsak** [comment]
Have a look how Cube docs link it. I think that way would make it work as we want to.

**Comment by bartoszmajsak** [comment]
Pushed upstream @07be60e

**Pull request closed without merging**
