### PR TITLE
ARQ-1956 Add Instance to Before|AfterEnrichment events

### PR DESCRIPTION
**Pull request by aslakknutsen**

### CODE REVIEW

**Comment by smiklosovic** [comment]
@aslakknutsen would not we need test method access as well?

**Comment by smiklosovic** [comment]
i mean that observed enrichment events do not carry information about the test method they belong to

**Comment by aslakknutsen** [comment]
We could technically add the method as well, but method might not always be applicable. And even if you have the method, you can't provide method argument values via this..

**Comment by smiklosovic** [comment]
:+1:

**Comment by aslakknutsen** [comment]
Pushed upstream https://github.com/arquillian/arquillian-core/commit/8bf22a55c88b89284d5c62d5b31a8c06ff243c24

**Pull request closed without merging**
